# eureka 접속
server:
  port: 8761 # 기본 포트
eureka:
  instance:
    hostname: 133.186.132.193
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://192.168.0.70:8761/eureka/
    healthcheck:
      enabled: true